server:
  port: 8762
spring:
  application:
    name: eureka-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: eureka-hi-8762
    prefer-ip-address: true     #访问路径可以显示IP地址