server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: eureka-server-8761
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/ # http://${eureka.instance.hostname}:${server.port}/eureka/